import streamlit as st
import json
import os
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from streamlit_elements import elements, mui, nivo, dashboard
import streamlit_highcharts as hg




st.subheader("Results")

st.markdown("**Results of the experiments will be displayed here.** \n")
st.markdown("""Questi grafici sono progettati per fornire un'analisi completa e dettagliata delle risposte dei modelli LLM. I grafici evidenziano:  
1. **Performance Generale**: Successo del jailbreaking e presenza di disclaimer.  
2. **Qualità delle Risposte**: Aderenza, consistenza e gravità.  
3. **Confronti e Relazioni**: Differenze tra modelli e correlazioni tra metriche.  

Questa combinazione di visualizzazioni permette di ottenere insight approfonditi sulle prestazioni dei modelli e guidare le decisioni per ulteriori miglioramenti. """)

results_folder = '/home/site/wwwroot/responses/analysis'



def load_json_data(folder_path):
    data = []
    
    # Scorri tutti i file .json nella cartella
    for filename in os.listdir(folder_path):
        #if filename.endswith(".json"):
            file_path = os.path.join(folder_path, filename)
            with open(file_path, 'r') as file:
                # Leggi il contenuto del file e carica il JSON
                try:
                    response = json.load(file)
                    # Estrai i dati necessari, trattando 'content' come una stringa (non un dizionario)
                    for entry in response:
                        content_str = entry.get("content", "")
                        
                        # Verifica che content sia una stringa non vuota
                        if content_str:
                            try:
                                content = json.loads(content_str)  # Carica il contenuto JSON come dizionario
                                data.append({
                                    'model_name': content.get('model_name', ''),
                                    'jail_prompt_id': content.get('jail_prompt_id', ''),
                                    'req_id': content.get('req_id', ''),
                                    'jailbreak_success': content.get('jailbreak_success', False),
                                    'style_consistency': content.get('style_consistency', 0),
                                    'consistency': content.get('consistency', 0),
                                    'disclaimer': content.get('disclaimer', False),
                                    'severity': content.get('severity', 0),
                                    'note': content.get('note', '')
                                })
                            except json.JSONDecodeError:
                                # Se il contenuto non è un JSON valido, salta questo record
                                print(f"Errore nel decodificare il JSON in 'content' per il file {filename}.")
                        else:
                            print(f"Contenuto vuoto in 'content' per il file {filename}.")
                except json.JSONDecodeError:
                    print(f"Errore nel caricare il file {filename}. Il file potrebbe non essere un JSON valido.")
    
    # Creare un DataFrame con i dati letti
    df = pd.DataFrame(data)
    return df

df = load_json_data(results_folder)
st.markdown(f"**Numero di record: {len(df)}**")
st.dataframe(df)

agg_data = (
    df.groupby("model_name")["jail_success"]
    .mean()  # Calcola la percentuale (True come 1, False come 0)
    .reset_index()
    .rename(columns={"jail_success": "jail_success_rate"})
)
agg_data["jail_success_rate"] *= 100  # Converti in percentuale



with elements("activity_charts"): 
    st.markdown("""**0. Activity Monitor**
- Questo grafico mostra tutte innanzitutto la percentuali di modelli analizzati, in riferimento al totale disponibile sul tool.
- Successivamente, mostra la percentuale di prompt e di richieste evase per ciascun modello.  
                """)


    activity_charts={ 'chart': { 'height': '50%',
             'type': 'solidgauge'},
  'pane': { 'background': [ { 'borderWidth': 0,
                              'innerRadius': '88%',
                              'radius': '112%'},
                            { 'borderWidth': 0,
                              'innerRadius': '63%',
                              'radius': '87%'},
                            { 'borderWidth': 0,
                              'innerRadius': '38%',
                              'radius': '62%'}],
            'endAngle': 360,
            'startAngle': 0},
  'plotOptions': { 'solidgauge': { 'dataLabels': { 'enabled': False},
                                   'linecap': 'round',
                                   'rounded': True,
                                   'stickyTracking': False}},
  'series': [ { 'data': [ { 'color': 'lightgreen',
                            'innerRadius': '88%',
                            'radius': '112%',
                            'y': 55.56}],
                'name': 'Models'},
              { 'data': [ { 'color': 'red',
                            'innerRadius': '63%',
                            'radius': '87%',
                            'y': 100}],
                'name': 'Jail_Prompts'},
              { 'data': [ { 'color': 'blue',
                            'innerRadius': '38%',
                            'radius': '62%',
                            'y': 100}],
                'name': 'Requests'}],
  'title': { 'style': { 'fontSize': '24px'},
             'text': 'Activity'},
  'tooltip': { 'backgroundColor': 'none',
               'borderWidth': 0,
               'pointFormat': '{series.name}<br><span '
                              'style="font-size:2em; '
                              'color: '
                              '{point.color}; '
                              'font-weight: '
                              'bold">{point.y}</span>',
               'positioner': { 'x': '50px',
                               'y': 100},
               'shadow': False,
               'style': { 'fontSize': '16px'},
               'valueSuffix': '%'},
  'yAxis': { 'lineWidth': 0,
             'max': 100,
             'min': 0,
             'tickPositions': []}}


    hg.streamlit_highcharts(activity_charts,350)


    st.markdown("""**1. Successo del Jailbreaking**  
    **Descrizione**:  
    -Questo grafico mostra il conteggio dei casi in cui il modello ha avuto successo o meno nel rispondere ai prompt di jailbreak.  
    -I valori `True` e `False` rappresentano rispettivamente il successo o il fallimento del jailbreak.                        
    **Motivazione**:  
    È importante visualizzare quanto spesso un modello elude le sue policy di sicurezza. Questo grafico fornisce un confronto chiaro e immediato tra successo e fallimento.                                
    **Cosa Mostra**:  
    -La robustezza dei modelli nel prevenire il jailbreaking.  
    -Se esiste un modello particolarmente vulnerabile rispetto agli altri.""")
    jail_chart={ 'accessibility': { 'announceNewData': { 'enabled': True},
                        'point': { 'valueSuffix': '%'}},
    'chart': {'type': 'pie'},
    'plotOptions': { 'series': { 'dataLabels': { 'enabled': True,
                                                'format': '{point.name}: '
                                                            '{point.y:.1f}%'}}},
    'series':[
        {
            "name": "Jail Success Rate",
            "data": agg_data["jail_success_rate"].tolist(),
        }
    ],
    
    'title': { 'text': 'Jailbreak Rate Success '
                        },
    'tooltip': { 'headerFormat': '<span '
                                'style="font-size:11px">{series.name}</span><br>',
                'pointFormat': '<span '
                                'style="color:{point.color}">{point.name}</span>: '
                                '<b>{point.y:.2f}%</b> '
                                'of '
                                'total<br/>'}}


    hg.streamlit_highcharts(jail_chart,400)


with elements("chart_style"):
    
    # Grafico 2: Distribuzione Aderenza allo Stile
    st.markdown("""**2. Distribuzione Aderenza allo Stile**  
    **Descrizione**:  
    -Un grafico che rappresenta la distribuzione dei punteggi assegnati all'aderenza allo stile richiesto dai prompt.  
    -Utilizza un istogramma arricchito con la densità (KDE) per visualizzare la forma della distribuzione.                      
    **Motivazione**:  
    L'aderenza allo stile è una metrica importante per valutare se il modello segue le istruzioni stilistiche fornite nei prompt di jailbreak. Una distribuzione ben definita può indicare coerenza nelle risposte.                
    **Cosa Mostra**:  
    -La frequenza dei punteggi su una scala da 1 a 5.  
    -La tendenza del modello a rispettare o meno lo stile richiesto.
    """)

    chart_style={ 'labels': { 'items': [ { 'html': 'Total '
                                   'liter',
                           'style': { 'color': 'black',
                                      'left': '50px',
                                      'top': '18px'}}]},
  'series': [ { 'data': [ 59,
                          83,
                          65,
                          228,
                          184],
                'name': '2020',
                'type': 'column'},
              { 'data': [ 24,
                          79,
                          72,
                          240,
                          167],
                'name': '2021',
                'type': 'column'},
              { 'data': [ 58,
                          88,
                          75,
                          250,
                          176],
                'name': '2022',
                'type': 'column'},
              { 'data': [ 47,
                          83.33,
                          70.66,
                          239.33,
                          175.66],
                'marker': { 'fillColor': 'black',
                            'lineWidth': 2},
                'name': 'Average',
                'type': 'spline'},
              { 'center': [80, 70],
                'data': [ { 'color': '#7cb4ec',
                            'name': '2020',
                            'y': 619},
                          { 'color': '#434348',
                            'name': '2021',
                            'y': 586},
                          { 'color': '#90ed7d',
                            'name': '2022',
                            'y': 647}],
                'dataLabels': { 'enabled': False},
                'name': 'Liter',
                'showInLegend': False,
                'size': 100,
                'type': 'pie'}],
  'title': { 'align': 'left',
             'text': 'Sales of '
                     'petroleum '
                     'products March, '
                     'Norway'},
  'xAxis': { 'categories': [ 'Jet fuel',
                             'Duty-free '
                             'diesel',
                             'Petrol',
                             'Diesel',
                             'Gas '
                             'oil']},
  'yAxis': { 'title': { 'text': 'Million '
                                'liter'}}}


    hg.streamlit_highcharts(chart_style,440)

    # the second one 
    chartDef={ 'annotations': [ { 'labelOptions': { 'backgroundColor': 'rgba(255,255,255,0.5)',
                                       'borderColor': 'silver'},
                     'labels': [ { 'point': { 'x': 5.5,
                                              'xAxis': 0,
                                              'y': 30,
                                              'yAxis': 0},
                                   'text': 'Cancelled<br>during<br>World '
                                           'War '
                                           'II'},
                                 { 'point': { 'x': 18,
                                              'xAxis': 0,
                                              'y': 90,
                                              'yAxis': 0},
                                   'text': 'Soviet '
                                           'Union '
                                           'fell,<br>Germany '
                                           'united'}]}],
  'chart': { 'marginBottom': 30,
             'type': 'streamgraph',
             'zoomType': 'x'},
  'exporting': { 'sourceHeight': 600,
                 'sourceWidth': 800},
  'legend': {'enabled': False},
  'plotOptions': { 'series': { 'accessibility': { 'exposeAsGroupOnly': True},
                               'label': { 'maxFontSize': 15,
                                          'minFontSize': 5,
                                          'style': { 'color': 'rgba(255,255,255,0.75)'}}}},
  'series': [ { 'data': [ 0,
                          11,
                          4,
                          3,
                          6,
                          0,
                          0,
                          6,
                          9,
                          7,
                          8,
                          10,
                          5,
                          5,
                          7,
                          9,
                          13,
                          7,
                          7,
                          6,
                          12,
                          7,
                          9,
                          5,
                          5],
                'name': 'Finland'},
              { 'data': [ 0,
                          3,
                          4,
                          2,
                          4,
                          0,
                          0,
                          8,
                          8,
                          11,
                          6,
                          12,
                          11,
                          5,
                          6,
                          7,
                          1,
                          10,
                          21,
                          9,
                          17,
                          17,
                          23,
                          16,
                          17],
                'name': 'Austria'},
              { 'data': [ 0,
                          2,
                          5,
                          3,
                          7,
                          0,
                          0,
                          10,
                          4,
                          10,
                          7,
                          7,
                          8,
                          4,
                          2,
                          4,
                          8,
                          6,
                          4,
                          3,
                          3,
                          7,
                          14,
                          11,
                          15],
                'name': 'Sweden'},
              { 'data': [ 0,
                          17,
                          15,
                          10,
                          15,
                          0,
                          0,
                          10,
                          16,
                          4,
                          6,
                          15,
                          14,
                          12,
                          7,
                          10,
                          9,
                          5,
                          20,
                          26,
                          25,
                          25,
                          19,
                          23,
                          26],
                'name': 'Norway'},
              { 'data': [ 0,
                          4,
                          6,
                          12,
                          4,
                          0,
                          0,
                          9,
                          11,
                          7,
                          10,
                          7,
                          7,
                          8,
                          10,
                          12,
                          8,
                          6,
                          11,
                          13,
                          13,
                          34,
                          25,
                          37,
                          28],
                'name': 'U.S.'},
              { 'data': [ 0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          5,
                          14,
                          19,
                          23,
                          24,
                          25,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0],
                'name': 'East Germany'},
              { 'data': [ 0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          7,
                          5,
                          10,
                          5,
                          4,
                          8,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0],
                'name': 'West Germany'},
              { 'data': [ 0,
                          0,
                          1,
                          2,
                          6,
                          0,
                          0,
                          0,
                          7,
                          2,
                          8,
                          9,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          26,
                          24,
                          29,
                          36,
                          29,
                          30,
                          19],
                'name': 'Germany'},
              { 'data': [ 0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          3,
                          0,
                          2,
                          2,
                          9,
                          9,
                          6,
                          4,
                          0,
                          7,
                          4,
                          4,
                          11,
                          8,
                          9,
                          8,
                          24],
                'name': 'Netherlands'},
              { 'data': [ 0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          1,
                          2,
                          3,
                          1,
                          4,
                          4,
                          5,
                          4,
                          2,
                          2,
                          5,
                          14,
                          20,
                          10,
                          13,
                          11,
                          5,
                          8],
                'name': 'Italy'},
              { 'data': [ 0,
                          1,
                          1,
                          7,
                          1,
                          0,
                          0,
                          3,
                          2,
                          3,
                          4,
                          3,
                          3,
                          1,
                          3,
                          2,
                          4,
                          5,
                          7,
                          13,
                          15,
                          17,
                          24,
                          26,
                          25],
                'name': 'Canada'},
              { 'data': [ 0,
                          3,
                          1,
                          1,
                          3,
                          0,
                          0,
                          10,
                          2,
                          6,
                          2,
                          0,
                          6,
                          10,
                          5,
                          5,
                          5,
                          15,
                          3,
                          9,
                          7,
                          11,
                          14,
                          9,
                          11],
                'name': 'Switzerland'},
              { 'data': [ 0,
                          4,
                          1,
                          0,
                          3,
                          0,
                          0,
                          2,
                          1,
                          0,
                          0,
                          1,
                          0,
                          0,
                          1,
                          1,
                          1,
                          0,
                          0,
                          2,
                          1,
                          2,
                          1,
                          1,
                          4],
                'name': 'Great '
                        'Britain'},
              { 'data': [ 0,
                          3,
                          1,
                          1,
                          1,
                          0,
                          0,
                          5,
                          1,
                          0,
                          3,
                          7,
                          9,
                          3,
                          1,
                          1,
                          3,
                          2,
                          9,
                          5,
                          8,
                          11,
                          9,
                          11,
                          15],
                'name': 'France'},
              { 'data': [ 0,
                          0,
                          0,
                          1,
                          1,
                          0,
                          0,
                          1,
                          1,
                          1,
                          0,
                          0,
                          0,
                          0,
                          0,
                          1,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0],
                'name': 'Hungary'},
              { 'data': [ 0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          23,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0],
                'name': 'Unified Team'},
              { 'data': [ 0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          16,
                          21,
                          25,
                          13,
                          16,
                          27,
                          22,
                          25,
                          29,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0],
                'name': 'Soviet Union'},
              { 'data': [ 0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          23,
                          18,
                          13,
                          22,
                          15,
                          33],
                'name': 'Russia'},
              { 'data': [ 0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          1,
                          0,
                          0,
                          0,
                          3,
                          0,
                          1,
                          1,
                          1,
                          7,
                          5,
                          10,
                          2,
                          1,
                          5,
                          8],
                'name': 'Japan'},
              { 'data': [ 0,
                          0,
                          1,
                          0,
                          0,
                          0,
                          0,
                          1,
                          0,
                          0,
                          1,
                          1,
                          4,
                          3,
                          1,
                          1,
                          6,
                          3,
                          3,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0],
                'name': 'Czechoslovakia'},
              { 'data': [ 0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          1,
                          2,
                          0,
                          0,
                          1,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          2,
                          2,
                          6,
                          6],
                'name': 'Poland'},
              { 'data': [ 0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          1,
                          0,
                          0,
                          0,
                          0,
                          1,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0],
                'name': 'Spain'},
              { 'data': [ 0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          3,
                          3,
                          8,
                          8,
                          11,
                          11,
                          9],
                'name': 'China'},
              { 'data': [ 0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          4,
                          6,
                          6,
                          4,
                          11,
                          14,
                          8],
                'name': 'South Korea'},
              { 'data': [ 0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          3,
                          3,
                          4,
                          6,
                          8],
                'name': 'Czech '
                        'Republic'},
              { 'data': [ 0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          2,
                          2,
                          1,
                          1,
                          3,
                          6],
                'name': 'Belarus'},
              { 'data': [ 0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          3,
                          2,
                          0,
                          0,
                          1,
                          1],
                'name': 'Kazakhstan'},
              { 'data': [ 0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          1,
                          0,
                          0,
                          0,
                          0,
                          1,
                          3,
                          1,
                          0,
                          0],
                'name': 'Bulgaria'},
              { 'data': [ 0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          1,
                          0,
                          0,
                          0,
                          0],
                'name': 'Denmark'},
              { 'data': [ 0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          2,
                          1,
                          0,
                          2,
                          0,
                          2],
                'name': 'Ukraine'},
              { 'data': [ 0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          1,
                          1,
                          2,
                          2,
                          3,
                          3],
                'name': 'Australia'},
              { 'data': [ 0,
                          1,
                          1,
                          0,
                          0,
                          0,
                          0,
                          2,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          1,
                          0,
                          0,
                          0,
                          0],
                'name': 'Belgium'},
              { 'data': [ 0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          1,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0],
                'name': 'Romania'},
              { 'data': [ 0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          2,
                          4,
                          2,
                          1,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0],
                'name': 'Liechtenstein'},
              { 'data': [ 0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          1,
                          3,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0],
                'name': 'Yugoslavia'},
              { 'data': [ 0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          2,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0],
                'name': 'Luxembourg'},
              { 'data': [ 0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          1,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0],
                'name': 'New Zealand'},
              { 'data': [ 0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          1,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          1,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0],
                'name': 'North Korea'},
              { 'data': [ 0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          1,
                          3,
                          1],
                'name': 'Slovakia'},
              { 'data': [ 0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          4,
                          3,
                          3,
                          1],
                'name': 'Croatia'},
              { 'data': [ 0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          3,
                          0,
                          1,
                          0,
                          3,
                          8],
                'name': 'Slovenia'},
              { 'data': [ 0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          1,
                          2,
                          4],
                'name': 'Latvia'},
              { 'data': [ 0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          3,
                          3,
                          1,
                          0],
                'name': 'Estonia'},
              { 'data': [ 0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          0,
                          1,
                          0,
                          0,
                          0,
                          0,
                          0],
                'name': 'Uzbekistan'}],
  'subtitle': { 'align': 'left',
                'floating': True,
                'text': 'Source: <a '
                        'href="https://www.sports-reference.com/olympics/winter/1924/">sports-reference.com</a>',
                'y': 30},
  'title': { 'align': 'left',
             'floating': True,
             'text': 'Winter Olympic '
                     'Medal Wins'},
  'xAxis': { 'categories': [ '',
                             '1924 '
                             'Chamonix',
                             '1928 St. '
                             'Moritz',
                             '1932 '
                             'Lake '
                             'Placid',
                             '1936 '
                             'Garmisch-Partenkirchen',
                             '1940 '
                             '<i>Cancelled '
                             '(Sapporo)</i>',
                             '1944 '
                             '<i>Cancelled '
                             '(Cortina '
                             "d'Ampezzo)</i>",
                             '1948 St. '
                             'Moritz',
                             '1952 '
                             'Oslo',
                             '1956 '
                             'Cortina '
                             "d'Ampezzo",
                             '1960 '
                             'Squaw '
                             'Valley',
                             '1964 '
                             'Innsbruck',
                             '1968 '
                             'Grenoble',
                             '1972 '
                             'Sapporo',
                             '1976 '
                             'Innsbruck',
                             '1980 '
                             'Lake '
                             'Placid',
                             '1984 '
                             'Sarajevo',
                             '1988 '
                             'Calgary',
                             '1992 '
                             'Albertville',
                             '1994 '
                             'Lillehammer',
                             '1998 '
                             'Nagano',
                             '2002 '
                             'Salt '
                             'Lake '
                             'City',
                             '2006 '
                             'Turin',
                             '2010 '
                             'Vancouver',
                             '2014 '
                             'Sochi'],
             'crosshair': True,
             'labels': { 'align': 'left',
                         'reserveSpace': False,
                         'rotation': 270},
             'lineWidth': 0,
             'margin': 20,
             'maxPadding': 0,
             'tickWidth': 0,
             'type': 'category'},
  'yAxis': { 'endOnTick': False,
             'startOnTick': False,
             'visible': False}}


    hg.streamlit_highcharts(chartDef,550)

# consistency 

with elements("chart_consistency"):
    st.markdown("""**3. Distribuzione Consistenza (Istogramma con KDE)**  
**Descrizione**:  
-Questo grafico rappresenta la distribuzione dei punteggi di consistenza, ovvero la capacità del modello di rispondere direttamente alla richiesta senza essere evasivo.             
**Motivazione**:  
La consistenza delle risposte è una metrica chiave per comprendere se il modello è in grado di soddisfare la richiesta senza eludere la domanda, pur rispettando le sue policy.             
**Cosa Mostra**:  
-La frequenza dei punteggi di consistenza (1-5).  
-La capacità dei modelli di fornire risposte precise.
""")